/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.observertc.webrtc.common.reports.avro;
@org.apache.avro.specific.AvroGenerated
public enum MediaType implements org.apache.avro.generic.GenericEnumSymbol<MediaType> {
  AUDIO, VIDEO, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MediaType\",\"namespace\":\"org.observertc.webrtc.common.reports.avro\",\"symbols\":[\"AUDIO\",\"VIDEO\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
