/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.observertc.webrtc.schemas.reports;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InitiatedCall extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4454150732927543663L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InitiatedCall\",\"namespace\":\"org.observertc.webrtc.schemas.reports\",\"fields\":[{\"name\":\"callUUID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"callName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InitiatedCall> ENCODER =
      new BinaryMessageEncoder<InitiatedCall>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InitiatedCall> DECODER =
      new BinaryMessageDecoder<InitiatedCall>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InitiatedCall> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InitiatedCall> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InitiatedCall> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InitiatedCall>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InitiatedCall to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InitiatedCall from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InitiatedCall instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InitiatedCall fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String callUUID;
   private java.lang.String callName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InitiatedCall() {}

  /**
   * All-args constructor.
   * @param callUUID The new value for callUUID
   * @param callName The new value for callName
   */
  public InitiatedCall(java.lang.String callUUID, java.lang.String callName) {
    this.callUUID = callUUID;
    this.callName = callName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return callUUID;
    case 1: return callName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: callUUID = value$ != null ? value$.toString() : null; break;
    case 1: callName = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'callUUID' field.
   * @return The value of the 'callUUID' field.
   */
  public java.lang.String getCallUUID() {
    return callUUID;
  }



  /**
   * Gets the value of the 'callName' field.
   * @return The value of the 'callName' field.
   */
  public java.lang.String getCallName() {
    return callName;
  }



  /**
   * Creates a new InitiatedCall RecordBuilder.
   * @return A new InitiatedCall RecordBuilder
   */
  public static org.observertc.webrtc.schemas.reports.InitiatedCall.Builder newBuilder() {
    return new org.observertc.webrtc.schemas.reports.InitiatedCall.Builder();
  }

  /**
   * Creates a new InitiatedCall RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InitiatedCall RecordBuilder
   */
  public static org.observertc.webrtc.schemas.reports.InitiatedCall.Builder newBuilder(org.observertc.webrtc.schemas.reports.InitiatedCall.Builder other) {
    if (other == null) {
      return new org.observertc.webrtc.schemas.reports.InitiatedCall.Builder();
    } else {
      return new org.observertc.webrtc.schemas.reports.InitiatedCall.Builder(other);
    }
  }

  /**
   * Creates a new InitiatedCall RecordBuilder by copying an existing InitiatedCall instance.
   * @param other The existing instance to copy.
   * @return A new InitiatedCall RecordBuilder
   */
  public static org.observertc.webrtc.schemas.reports.InitiatedCall.Builder newBuilder(org.observertc.webrtc.schemas.reports.InitiatedCall other) {
    if (other == null) {
      return new org.observertc.webrtc.schemas.reports.InitiatedCall.Builder();
    } else {
      return new org.observertc.webrtc.schemas.reports.InitiatedCall.Builder(other);
    }
  }

  /**
   * RecordBuilder for InitiatedCall instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InitiatedCall>
    implements org.apache.avro.data.RecordBuilder<InitiatedCall> {

    private java.lang.String callUUID;
    private java.lang.String callName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.observertc.webrtc.schemas.reports.InitiatedCall.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.callUUID)) {
        this.callUUID = data().deepCopy(fields()[0].schema(), other.callUUID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.callName)) {
        this.callName = data().deepCopy(fields()[1].schema(), other.callName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing InitiatedCall instance
     * @param other The existing instance to copy.
     */
    private Builder(org.observertc.webrtc.schemas.reports.InitiatedCall other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.callUUID)) {
        this.callUUID = data().deepCopy(fields()[0].schema(), other.callUUID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.callName)) {
        this.callName = data().deepCopy(fields()[1].schema(), other.callName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'callUUID' field.
      * @return The value.
      */
    public java.lang.String getCallUUID() {
      return callUUID;
    }


    /**
      * Sets the value of the 'callUUID' field.
      * @param value The value of 'callUUID'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.InitiatedCall.Builder setCallUUID(java.lang.String value) {
      validate(fields()[0], value);
      this.callUUID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'callUUID' field has been set.
      * @return True if the 'callUUID' field has been set, false otherwise.
      */
    public boolean hasCallUUID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'callUUID' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.InitiatedCall.Builder clearCallUUID() {
      callUUID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'callName' field.
      * @return The value.
      */
    public java.lang.String getCallName() {
      return callName;
    }


    /**
      * Sets the value of the 'callName' field.
      * @param value The value of 'callName'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.InitiatedCall.Builder setCallName(java.lang.String value) {
      validate(fields()[1], value);
      this.callName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'callName' field has been set.
      * @return True if the 'callName' field has been set, false otherwise.
      */
    public boolean hasCallName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'callName' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.InitiatedCall.Builder clearCallName() {
      callName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InitiatedCall build() {
      try {
        InitiatedCall record = new InitiatedCall();
        record.callUUID = fieldSetFlags()[0] ? this.callUUID : (java.lang.String) defaultValue(fields()[0]);
        record.callName = fieldSetFlags()[1] ? this.callName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InitiatedCall>
    WRITER$ = (org.apache.avro.io.DatumWriter<InitiatedCall>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InitiatedCall>
    READER$ = (org.apache.avro.io.DatumReader<InitiatedCall>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.callUUID);

    if (this.callName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.callName);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.callUUID = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.callName = null;
      } else {
        this.callName = in.readString();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.callUUID = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.callName = null;
          } else {
            this.callName = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










