/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.observertc.webrtc.schemas.reports;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RemoteInboundRTP extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1408063795961423643L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RemoteInboundRTP\",\"namespace\":\"org.observertc.webrtc.schemas.reports\",\"fields\":[{\"name\":\"mediaUnitId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"callName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"userId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"browserId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"peerConnectionUUID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ssrc\",\"type\":\"long\"},{\"name\":\"codecID\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"jitter\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"localID\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"mediaType\",\"type\":{\"type\":\"enum\",\"name\":\"MediaType\",\"symbols\":[\"AUDIO\",\"VIDEO\",\"UNKNOWN\",\"NULL\"]},\"default\":\"UNKNOWN\"},{\"name\":\"packetsLost\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"roundTripTime\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"transportID\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RemoteInboundRTP> ENCODER =
      new BinaryMessageEncoder<RemoteInboundRTP>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RemoteInboundRTP> DECODER =
      new BinaryMessageDecoder<RemoteInboundRTP>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RemoteInboundRTP> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RemoteInboundRTP> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RemoteInboundRTP> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RemoteInboundRTP>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RemoteInboundRTP to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RemoteInboundRTP from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RemoteInboundRTP instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RemoteInboundRTP fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String mediaUnitId;
   private java.lang.String callName;
   private java.lang.String userId;
   private java.lang.String browserId;
   private java.lang.String peerConnectionUUID;
   private long ssrc;
   private java.lang.String codecID;
   private java.lang.String id;
   private java.lang.Float jitter;
   private java.lang.String localID;
   private org.observertc.webrtc.schemas.reports.MediaType mediaType;
   private java.lang.Integer packetsLost;
   private java.lang.Double roundTripTime;
   private java.lang.String transportID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RemoteInboundRTP() {}

  /**
   * All-args constructor.
   * @param mediaUnitId The new value for mediaUnitId
   * @param callName The new value for callName
   * @param userId The new value for userId
   * @param browserId The new value for browserId
   * @param peerConnectionUUID The new value for peerConnectionUUID
   * @param ssrc The new value for ssrc
   * @param codecID The new value for codecID
   * @param id The new value for id
   * @param jitter The new value for jitter
   * @param localID The new value for localID
   * @param mediaType The new value for mediaType
   * @param packetsLost The new value for packetsLost
   * @param roundTripTime The new value for roundTripTime
   * @param transportID The new value for transportID
   */
  public RemoteInboundRTP(java.lang.String mediaUnitId, java.lang.String callName, java.lang.String userId, java.lang.String browserId, java.lang.String peerConnectionUUID, java.lang.Long ssrc, java.lang.String codecID, java.lang.String id, java.lang.Float jitter, java.lang.String localID, org.observertc.webrtc.schemas.reports.MediaType mediaType, java.lang.Integer packetsLost, java.lang.Double roundTripTime, java.lang.String transportID) {
    this.mediaUnitId = mediaUnitId;
    this.callName = callName;
    this.userId = userId;
    this.browserId = browserId;
    this.peerConnectionUUID = peerConnectionUUID;
    this.ssrc = ssrc;
    this.codecID = codecID;
    this.id = id;
    this.jitter = jitter;
    this.localID = localID;
    this.mediaType = mediaType;
    this.packetsLost = packetsLost;
    this.roundTripTime = roundTripTime;
    this.transportID = transportID;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mediaUnitId;
    case 1: return callName;
    case 2: return userId;
    case 3: return browserId;
    case 4: return peerConnectionUUID;
    case 5: return ssrc;
    case 6: return codecID;
    case 7: return id;
    case 8: return jitter;
    case 9: return localID;
    case 10: return mediaType;
    case 11: return packetsLost;
    case 12: return roundTripTime;
    case 13: return transportID;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mediaUnitId = value$ != null ? value$.toString() : null; break;
    case 1: callName = value$ != null ? value$.toString() : null; break;
    case 2: userId = value$ != null ? value$.toString() : null; break;
    case 3: browserId = value$ != null ? value$.toString() : null; break;
    case 4: peerConnectionUUID = value$ != null ? value$.toString() : null; break;
    case 5: ssrc = (java.lang.Long)value$; break;
    case 6: codecID = value$ != null ? value$.toString() : null; break;
    case 7: id = value$ != null ? value$.toString() : null; break;
    case 8: jitter = (java.lang.Float)value$; break;
    case 9: localID = value$ != null ? value$.toString() : null; break;
    case 10: mediaType = (org.observertc.webrtc.schemas.reports.MediaType)value$; break;
    case 11: packetsLost = (java.lang.Integer)value$; break;
    case 12: roundTripTime = (java.lang.Double)value$; break;
    case 13: transportID = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'mediaUnitId' field.
   * @return The value of the 'mediaUnitId' field.
   */
  public java.lang.String getMediaUnitId() {
    return mediaUnitId;
  }



  /**
   * Gets the value of the 'callName' field.
   * @return The value of the 'callName' field.
   */
  public java.lang.String getCallName() {
    return callName;
  }



  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }



  /**
   * Gets the value of the 'browserId' field.
   * @return The value of the 'browserId' field.
   */
  public java.lang.String getBrowserId() {
    return browserId;
  }



  /**
   * Gets the value of the 'peerConnectionUUID' field.
   * @return The value of the 'peerConnectionUUID' field.
   */
  public java.lang.String getPeerConnectionUUID() {
    return peerConnectionUUID;
  }



  /**
   * Gets the value of the 'ssrc' field.
   * @return The value of the 'ssrc' field.
   */
  public long getSsrc() {
    return ssrc;
  }



  /**
   * Gets the value of the 'codecID' field.
   * @return The value of the 'codecID' field.
   */
  public java.lang.String getCodecID() {
    return codecID;
  }



  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }



  /**
   * Gets the value of the 'jitter' field.
   * @return The value of the 'jitter' field.
   */
  public java.lang.Float getJitter() {
    return jitter;
  }



  /**
   * Gets the value of the 'localID' field.
   * @return The value of the 'localID' field.
   */
  public java.lang.String getLocalID() {
    return localID;
  }



  /**
   * Gets the value of the 'mediaType' field.
   * @return The value of the 'mediaType' field.
   */
  public org.observertc.webrtc.schemas.reports.MediaType getMediaType() {
    return mediaType;
  }



  /**
   * Gets the value of the 'packetsLost' field.
   * @return The value of the 'packetsLost' field.
   */
  public java.lang.Integer getPacketsLost() {
    return packetsLost;
  }



  /**
   * Gets the value of the 'roundTripTime' field.
   * @return The value of the 'roundTripTime' field.
   */
  public java.lang.Double getRoundTripTime() {
    return roundTripTime;
  }



  /**
   * Gets the value of the 'transportID' field.
   * @return The value of the 'transportID' field.
   */
  public java.lang.String getTransportID() {
    return transportID;
  }



  /**
   * Creates a new RemoteInboundRTP RecordBuilder.
   * @return A new RemoteInboundRTP RecordBuilder
   */
  public static org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder newBuilder() {
    return new org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder();
  }

  /**
   * Creates a new RemoteInboundRTP RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RemoteInboundRTP RecordBuilder
   */
  public static org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder newBuilder(org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder other) {
    if (other == null) {
      return new org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder();
    } else {
      return new org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder(other);
    }
  }

  /**
   * Creates a new RemoteInboundRTP RecordBuilder by copying an existing RemoteInboundRTP instance.
   * @param other The existing instance to copy.
   * @return A new RemoteInboundRTP RecordBuilder
   */
  public static org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder newBuilder(org.observertc.webrtc.schemas.reports.RemoteInboundRTP other) {
    if (other == null) {
      return new org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder();
    } else {
      return new org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder(other);
    }
  }

  /**
   * RecordBuilder for RemoteInboundRTP instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RemoteInboundRTP>
    implements org.apache.avro.data.RecordBuilder<RemoteInboundRTP> {

    private java.lang.String mediaUnitId;
    private java.lang.String callName;
    private java.lang.String userId;
    private java.lang.String browserId;
    private java.lang.String peerConnectionUUID;
    private long ssrc;
    private java.lang.String codecID;
    private java.lang.String id;
    private java.lang.Float jitter;
    private java.lang.String localID;
    private org.observertc.webrtc.schemas.reports.MediaType mediaType;
    private java.lang.Integer packetsLost;
    private java.lang.Double roundTripTime;
    private java.lang.String transportID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mediaUnitId)) {
        this.mediaUnitId = data().deepCopy(fields()[0].schema(), other.mediaUnitId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.callName)) {
        this.callName = data().deepCopy(fields()[1].schema(), other.callName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.browserId)) {
        this.browserId = data().deepCopy(fields()[3].schema(), other.browserId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.peerConnectionUUID)) {
        this.peerConnectionUUID = data().deepCopy(fields()[4].schema(), other.peerConnectionUUID);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.ssrc)) {
        this.ssrc = data().deepCopy(fields()[5].schema(), other.ssrc);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.codecID)) {
        this.codecID = data().deepCopy(fields()[6].schema(), other.codecID);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.id)) {
        this.id = data().deepCopy(fields()[7].schema(), other.id);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.jitter)) {
        this.jitter = data().deepCopy(fields()[8].schema(), other.jitter);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.localID)) {
        this.localID = data().deepCopy(fields()[9].schema(), other.localID);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.mediaType)) {
        this.mediaType = data().deepCopy(fields()[10].schema(), other.mediaType);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.packetsLost)) {
        this.packetsLost = data().deepCopy(fields()[11].schema(), other.packetsLost);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.roundTripTime)) {
        this.roundTripTime = data().deepCopy(fields()[12].schema(), other.roundTripTime);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.transportID)) {
        this.transportID = data().deepCopy(fields()[13].schema(), other.transportID);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing RemoteInboundRTP instance
     * @param other The existing instance to copy.
     */
    private Builder(org.observertc.webrtc.schemas.reports.RemoteInboundRTP other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.mediaUnitId)) {
        this.mediaUnitId = data().deepCopy(fields()[0].schema(), other.mediaUnitId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.callName)) {
        this.callName = data().deepCopy(fields()[1].schema(), other.callName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.browserId)) {
        this.browserId = data().deepCopy(fields()[3].schema(), other.browserId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.peerConnectionUUID)) {
        this.peerConnectionUUID = data().deepCopy(fields()[4].schema(), other.peerConnectionUUID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ssrc)) {
        this.ssrc = data().deepCopy(fields()[5].schema(), other.ssrc);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.codecID)) {
        this.codecID = data().deepCopy(fields()[6].schema(), other.codecID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.id)) {
        this.id = data().deepCopy(fields()[7].schema(), other.id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.jitter)) {
        this.jitter = data().deepCopy(fields()[8].schema(), other.jitter);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.localID)) {
        this.localID = data().deepCopy(fields()[9].schema(), other.localID);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.mediaType)) {
        this.mediaType = data().deepCopy(fields()[10].schema(), other.mediaType);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.packetsLost)) {
        this.packetsLost = data().deepCopy(fields()[11].schema(), other.packetsLost);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.roundTripTime)) {
        this.roundTripTime = data().deepCopy(fields()[12].schema(), other.roundTripTime);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.transportID)) {
        this.transportID = data().deepCopy(fields()[13].schema(), other.transportID);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'mediaUnitId' field.
      * @return The value.
      */
    public java.lang.String getMediaUnitId() {
      return mediaUnitId;
    }


    /**
      * Sets the value of the 'mediaUnitId' field.
      * @param value The value of 'mediaUnitId'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setMediaUnitId(java.lang.String value) {
      validate(fields()[0], value);
      this.mediaUnitId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mediaUnitId' field has been set.
      * @return True if the 'mediaUnitId' field has been set, false otherwise.
      */
    public boolean hasMediaUnitId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'mediaUnitId' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearMediaUnitId() {
      mediaUnitId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'callName' field.
      * @return The value.
      */
    public java.lang.String getCallName() {
      return callName;
    }


    /**
      * Sets the value of the 'callName' field.
      * @param value The value of 'callName'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setCallName(java.lang.String value) {
      validate(fields()[1], value);
      this.callName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'callName' field has been set.
      * @return True if the 'callName' field has been set, false otherwise.
      */
    public boolean hasCallName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'callName' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearCallName() {
      callName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setUserId(java.lang.String value) {
      validate(fields()[2], value);
      this.userId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'browserId' field.
      * @return The value.
      */
    public java.lang.String getBrowserId() {
      return browserId;
    }


    /**
      * Sets the value of the 'browserId' field.
      * @param value The value of 'browserId'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setBrowserId(java.lang.String value) {
      validate(fields()[3], value);
      this.browserId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'browserId' field has been set.
      * @return True if the 'browserId' field has been set, false otherwise.
      */
    public boolean hasBrowserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'browserId' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearBrowserId() {
      browserId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'peerConnectionUUID' field.
      * @return The value.
      */
    public java.lang.String getPeerConnectionUUID() {
      return peerConnectionUUID;
    }


    /**
      * Sets the value of the 'peerConnectionUUID' field.
      * @param value The value of 'peerConnectionUUID'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setPeerConnectionUUID(java.lang.String value) {
      validate(fields()[4], value);
      this.peerConnectionUUID = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'peerConnectionUUID' field has been set.
      * @return True if the 'peerConnectionUUID' field has been set, false otherwise.
      */
    public boolean hasPeerConnectionUUID() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'peerConnectionUUID' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearPeerConnectionUUID() {
      peerConnectionUUID = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'ssrc' field.
      * @return The value.
      */
    public long getSsrc() {
      return ssrc;
    }


    /**
      * Sets the value of the 'ssrc' field.
      * @param value The value of 'ssrc'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setSsrc(long value) {
      validate(fields()[5], value);
      this.ssrc = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'ssrc' field has been set.
      * @return True if the 'ssrc' field has been set, false otherwise.
      */
    public boolean hasSsrc() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'ssrc' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearSsrc() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'codecID' field.
      * @return The value.
      */
    public java.lang.String getCodecID() {
      return codecID;
    }


    /**
      * Sets the value of the 'codecID' field.
      * @param value The value of 'codecID'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setCodecID(java.lang.String value) {
      validate(fields()[6], value);
      this.codecID = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'codecID' field has been set.
      * @return True if the 'codecID' field has been set, false otherwise.
      */
    public boolean hasCodecID() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'codecID' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearCodecID() {
      codecID = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setId(java.lang.String value) {
      validate(fields()[7], value);
      this.id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearId() {
      id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'jitter' field.
      * @return The value.
      */
    public java.lang.Float getJitter() {
      return jitter;
    }


    /**
      * Sets the value of the 'jitter' field.
      * @param value The value of 'jitter'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setJitter(java.lang.Float value) {
      validate(fields()[8], value);
      this.jitter = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'jitter' field has been set.
      * @return True if the 'jitter' field has been set, false otherwise.
      */
    public boolean hasJitter() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'jitter' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearJitter() {
      jitter = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'localID' field.
      * @return The value.
      */
    public java.lang.String getLocalID() {
      return localID;
    }


    /**
      * Sets the value of the 'localID' field.
      * @param value The value of 'localID'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setLocalID(java.lang.String value) {
      validate(fields()[9], value);
      this.localID = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'localID' field has been set.
      * @return True if the 'localID' field has been set, false otherwise.
      */
    public boolean hasLocalID() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'localID' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearLocalID() {
      localID = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'mediaType' field.
      * @return The value.
      */
    public org.observertc.webrtc.schemas.reports.MediaType getMediaType() {
      return mediaType;
    }


    /**
      * Sets the value of the 'mediaType' field.
      * @param value The value of 'mediaType'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setMediaType(org.observertc.webrtc.schemas.reports.MediaType value) {
      validate(fields()[10], value);
      this.mediaType = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'mediaType' field has been set.
      * @return True if the 'mediaType' field has been set, false otherwise.
      */
    public boolean hasMediaType() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'mediaType' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearMediaType() {
      mediaType = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'packetsLost' field.
      * @return The value.
      */
    public java.lang.Integer getPacketsLost() {
      return packetsLost;
    }


    /**
      * Sets the value of the 'packetsLost' field.
      * @param value The value of 'packetsLost'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setPacketsLost(java.lang.Integer value) {
      validate(fields()[11], value);
      this.packetsLost = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'packetsLost' field has been set.
      * @return True if the 'packetsLost' field has been set, false otherwise.
      */
    public boolean hasPacketsLost() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'packetsLost' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearPacketsLost() {
      packetsLost = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'roundTripTime' field.
      * @return The value.
      */
    public java.lang.Double getRoundTripTime() {
      return roundTripTime;
    }


    /**
      * Sets the value of the 'roundTripTime' field.
      * @param value The value of 'roundTripTime'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setRoundTripTime(java.lang.Double value) {
      validate(fields()[12], value);
      this.roundTripTime = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'roundTripTime' field has been set.
      * @return True if the 'roundTripTime' field has been set, false otherwise.
      */
    public boolean hasRoundTripTime() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'roundTripTime' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearRoundTripTime() {
      roundTripTime = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'transportID' field.
      * @return The value.
      */
    public java.lang.String getTransportID() {
      return transportID;
    }


    /**
      * Sets the value of the 'transportID' field.
      * @param value The value of 'transportID'.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder setTransportID(java.lang.String value) {
      validate(fields()[13], value);
      this.transportID = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'transportID' field has been set.
      * @return True if the 'transportID' field has been set, false otherwise.
      */
    public boolean hasTransportID() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'transportID' field.
      * @return This builder.
      */
    public org.observertc.webrtc.schemas.reports.RemoteInboundRTP.Builder clearTransportID() {
      transportID = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RemoteInboundRTP build() {
      try {
        RemoteInboundRTP record = new RemoteInboundRTP();
        record.mediaUnitId = fieldSetFlags()[0] ? this.mediaUnitId : (java.lang.String) defaultValue(fields()[0]);
        record.callName = fieldSetFlags()[1] ? this.callName : (java.lang.String) defaultValue(fields()[1]);
        record.userId = fieldSetFlags()[2] ? this.userId : (java.lang.String) defaultValue(fields()[2]);
        record.browserId = fieldSetFlags()[3] ? this.browserId : (java.lang.String) defaultValue(fields()[3]);
        record.peerConnectionUUID = fieldSetFlags()[4] ? this.peerConnectionUUID : (java.lang.String) defaultValue(fields()[4]);
        record.ssrc = fieldSetFlags()[5] ? this.ssrc : (java.lang.Long) defaultValue(fields()[5]);
        record.codecID = fieldSetFlags()[6] ? this.codecID : (java.lang.String) defaultValue(fields()[6]);
        record.id = fieldSetFlags()[7] ? this.id : (java.lang.String) defaultValue(fields()[7]);
        record.jitter = fieldSetFlags()[8] ? this.jitter : (java.lang.Float) defaultValue(fields()[8]);
        record.localID = fieldSetFlags()[9] ? this.localID : (java.lang.String) defaultValue(fields()[9]);
        record.mediaType = fieldSetFlags()[10] ? this.mediaType : (org.observertc.webrtc.schemas.reports.MediaType) defaultValue(fields()[10]);
        record.packetsLost = fieldSetFlags()[11] ? this.packetsLost : (java.lang.Integer) defaultValue(fields()[11]);
        record.roundTripTime = fieldSetFlags()[12] ? this.roundTripTime : (java.lang.Double) defaultValue(fields()[12]);
        record.transportID = fieldSetFlags()[13] ? this.transportID : (java.lang.String) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RemoteInboundRTP>
    WRITER$ = (org.apache.avro.io.DatumWriter<RemoteInboundRTP>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RemoteInboundRTP>
    READER$ = (org.apache.avro.io.DatumReader<RemoteInboundRTP>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.mediaUnitId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.mediaUnitId);
    }

    if (this.callName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.callName);
    }

    if (this.userId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.userId);
    }

    if (this.browserId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.browserId);
    }

    out.writeString(this.peerConnectionUUID);

    out.writeLong(this.ssrc);

    if (this.codecID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.codecID);
    }

    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.id);
    }

    if (this.jitter == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.jitter);
    }

    if (this.localID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.localID);
    }

    out.writeEnum(this.mediaType.ordinal());

    if (this.packetsLost == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.packetsLost);
    }

    if (this.roundTripTime == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.roundTripTime);
    }

    if (this.transportID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.transportID);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.mediaUnitId = null;
      } else {
        this.mediaUnitId = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.callName = null;
      } else {
        this.callName = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.userId = null;
      } else {
        this.userId = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.browserId = null;
      } else {
        this.browserId = in.readString();
      }

      this.peerConnectionUUID = in.readString();

      this.ssrc = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.codecID = null;
      } else {
        this.codecID = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.jitter = null;
      } else {
        this.jitter = in.readFloat();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.localID = null;
      } else {
        this.localID = in.readString();
      }

      this.mediaType = org.observertc.webrtc.schemas.reports.MediaType.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.packetsLost = null;
      } else {
        this.packetsLost = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.roundTripTime = null;
      } else {
        this.roundTripTime = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.transportID = null;
      } else {
        this.transportID = in.readString();
      }

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.mediaUnitId = null;
          } else {
            this.mediaUnitId = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.callName = null;
          } else {
            this.callName = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.userId = null;
          } else {
            this.userId = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.browserId = null;
          } else {
            this.browserId = in.readString();
          }
          break;

        case 4:
          this.peerConnectionUUID = in.readString();
          break;

        case 5:
          this.ssrc = in.readLong();
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.codecID = null;
          } else {
            this.codecID = in.readString();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readString();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.jitter = null;
          } else {
            this.jitter = in.readFloat();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.localID = null;
          } else {
            this.localID = in.readString();
          }
          break;

        case 10:
          this.mediaType = org.observertc.webrtc.schemas.reports.MediaType.values()[in.readEnum()];
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.packetsLost = null;
          } else {
            this.packetsLost = in.readInt();
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.roundTripTime = null;
          } else {
            this.roundTripTime = in.readDouble();
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.transportID = null;
          } else {
            this.transportID = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










