package org.observertc.observer.sinks.mongo;

import org.bson.Document;
import org.observertc.observer.reports.ReportTypeVisitor;
import org.observertc.schemas.reports.*;

class ReportMapper implements ReportTypeVisitor<Object, Document> {

    @Override
    public Document visitObserverEventReport(Object payload) {
        var reportPayload = ((ObserverEventReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("sampleTimestamp", reportPayload.sampleTimestamp)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("name", reportPayload.name)
                .append("message", reportPayload.message)
                .append("value", reportPayload.value)
                .append("attachments", reportPayload.attachments)
                ;
    }

    @Override
    public Document visitCallEventReport(Object payload) {
        var reportPayload = ((CallEventReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("mediaTrackId", reportPayload.mediaTrackId)
                .append("SSRC", reportPayload.SSRC)
                .append("sampleTimestamp", reportPayload.sampleTimestamp)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("name", reportPayload.name)
                .append("message", reportPayload.message)
                .append("value", reportPayload.value)
                .append("attachments", reportPayload.attachments)
                ;
    }

    @Override
    public Document visitCallMetaDataReport(Object payload) {
        var reportPayload = ((CallMetaReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("sampleTimestamp", reportPayload.sampleTimestamp)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("type", reportPayload.type)
                .append("payload", reportPayload.payload)

                ;
    }

    @Override
    public Document visitClientDataChannelReport(Object payload) {
        var reportPayload = ((ClientDataChannelReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("peerConnectionLabel", reportPayload.peerConnectionLabel)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("label", reportPayload.label)
                .append("protocol", reportPayload.protocol)
                .append("state", reportPayload.state)
                .append("messagesSent", reportPayload.messagesSent)
                .append("bytesSent", reportPayload.bytesSent)
                .append("messagesReceived", reportPayload.messagesReceived)
                .append("bytesReceived", reportPayload.bytesReceived)

                ;

    }

    @Override
    public Document visitClientExtensionDataReport(Object payload) {
        var reportPayload = ((ClientExtensionReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("extensionType", reportPayload.extensionType)
                .append("payload", reportPayload.payload)

                ;

    }

    @Override
    public Document visitIceCandidatePairReport(Object payload) {
        var reportPayload = ((IceCandidatePairReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("label", reportPayload.label)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("transportId", reportPayload.transportId)
                .append("localCandidateId", reportPayload.localCandidateId)
                .append("remoteCandidateId", reportPayload.remoteCandidateId)
                .append("state", reportPayload.state)
                .append("nominated", reportPayload.nominated)
                .append("packetsSent", reportPayload.packetsSent)
                .append("packetsReceived", reportPayload.packetsReceived)
                .append("bytesSent", reportPayload.bytesSent)
                .append("bytesReceived", reportPayload.bytesReceived)
                .append("lastPacketSentTimestamp", reportPayload.lastPacketSentTimestamp)
                .append("lastPacketReceivedTimestamp", reportPayload.lastPacketReceivedTimestamp)
                .append("totalRoundTripTime", reportPayload.totalRoundTripTime)
                .append("currentRoundTripTime", reportPayload.currentRoundTripTime)
                .append("availableOutgoingBitrate", reportPayload.availableOutgoingBitrate)
                .append("availableIncomingBitrate", reportPayload.availableIncomingBitrate)
                .append("requestsReceived", reportPayload.requestsReceived)
                .append("requestsSent", reportPayload.requestsSent)
                .append("responsesReceived", reportPayload.responsesReceived)
                .append("responsesSent", reportPayload.responsesSent)
                .append("consentRequestsSent", reportPayload.consentRequestsSent)
                .append("packetsDiscardedOnSend", reportPayload.packetsDiscardedOnSend)
                .append("bytesDiscardedOnSend", reportPayload.bytesDiscardedOnSend)
                ;
    }

    @Override
    public Document visitPeerConnectionTransportReport(Object payload) {
        var reportPayload = ((PeerConnectionTransportReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("label", reportPayload.label)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("packetsSent", reportPayload.packetsSent)
                .append("packetsReceived", reportPayload.packetsReceived)
                .append("bytesSent", reportPayload.bytesSent)
                .append("bytesReceived", reportPayload.bytesReceived)
                .append("iceRole", reportPayload.iceRole)
                .append("iceLocalUsernameFragment", reportPayload.iceLocalUsernameFragment)
                .append("dtlsState", reportPayload.dtlsState)
                .append("selectedCandidatePairId", reportPayload.selectedCandidatePairId)
                .append("iceState", reportPayload.iceState)
                .append("localCertificateId", reportPayload.localCertificateId)
                .append("remoteCertificateId", reportPayload.remoteCertificateId)
                .append("tlsVersion", reportPayload.tlsVersion)
                .append("dtlsCipher", reportPayload.dtlsCipher)
                .append("srtpCipher", reportPayload.srtpCipher)
                .append("tlsGroup", reportPayload.tlsGroup)
                .append("selectedCandidatePairChanges", reportPayload.selectedCandidatePairChanges)
                ;

    }



    @Override
    public Document visitInboundAudioTrackReport(Object payload) {

        var reportPayload = ((InboundAudioTrackReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("label", reportPayload.label)
                .append("trackId", reportPayload.trackId)
                .append("sfuStreamId", reportPayload.sfuStreamId)
                .append("sfuSinkId", reportPayload.sfuSinkId)
                .append("remoteTrackId", reportPayload.remoteTrackId)
                .append("remoteUserId", reportPayload.remoteUserId)
                .append("remoteClientId", reportPayload.remoteClientId)
                .append("remotePeerConnectionId", reportPayload.remotePeerConnectionId)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("ssrc", reportPayload.ssrc)
                .append("packetsReceived", reportPayload.packetsReceived)
                .append("packetsLost", reportPayload.packetsLost)
                .append("jitter", reportPayload.jitter)
                .append("lastPacketReceivedTimestamp", reportPayload.lastPacketReceivedTimestamp)
                .append("headerBytesReceived", reportPayload.headerBytesReceived)
                .append("packetsDiscarded", reportPayload.packetsDiscarded)
                .append("fecPacketsReceived", reportPayload.fecPacketsReceived)
                .append("fecPacketsDiscarded", reportPayload.fecPacketsDiscarded)
                .append("bytesReceived", reportPayload.bytesReceived)
                .append("nackCount", reportPayload.nackCount)
                .append("totalProcessingDelay", reportPayload.totalProcessingDelay)
                .append("estimatedPlayoutTimestamp", reportPayload.estimatedPlayoutTimestamp)
                .append("jitterBufferDelay", reportPayload.jitterBufferDelay)
                .append("jitterBufferTargetDelay", reportPayload.jitterBufferTargetDelay)
                .append("jitterBufferEmittedCount", reportPayload.jitterBufferEmittedCount)
                .append("jitterBufferMinimumDelay", reportPayload.jitterBufferMinimumDelay)
                .append("totalSamplesReceived", reportPayload.totalSamplesReceived)
                .append("concealedSamples", reportPayload.concealedSamples)
                .append("silentConcealedSamples", reportPayload.silentConcealedSamples)
                .append("concealmentEvents", reportPayload.concealmentEvents)
                .append("insertedSamplesForDeceleration", reportPayload.insertedSamplesForDeceleration)
                .append("removedSamplesForAcceleration", reportPayload.removedSamplesForAcceleration)
                .append("audioLevel", reportPayload.audioLevel)
                .append("totalAudioEnergy", reportPayload.totalAudioEnergy)
                .append("totalSamplesDuration", reportPayload.totalSamplesDuration)
                .append("decoderImplementation", reportPayload.decoderImplementation)
                .append("packetsSent", reportPayload.packetsSent)
                .append("bytesSent", reportPayload.bytesSent)
                .append("remoteTimestamp", reportPayload.remoteTimestamp)
                .append("reportsSent", reportPayload.reportsSent)
                .append("roundTripTime", reportPayload.roundTripTime)
                .append("totalRoundTripTime", reportPayload.totalRoundTripTime)
                .append("roundTripTimeMeasurements", reportPayload.roundTripTimeMeasurements)
                .append("synthesizedSamplesDuration", reportPayload.synthesizedSamplesDuration)
                .append("synthesizedSamplesEvents", reportPayload.synthesizedSamplesEvents)
                .append("totalPlayoutDelay", reportPayload.totalPlayoutDelay)
                .append("totalSamplesCount", reportPayload.totalSamplesCount)
                ;
    }

    @Override
    public Document visitInboundVideoTrackReport(Object payload) {
        var reportPayload = ((InboundVideoTrackReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("label", reportPayload.label)
                .append("trackId", reportPayload.trackId)
                .append("sfuStreamId", reportPayload.sfuStreamId)
                .append("sfuSinkId", reportPayload.sfuSinkId)
                .append("remoteTrackId", reportPayload.remoteTrackId)
                .append("remoteUserId", reportPayload.remoteUserId)
                .append("remoteClientId", reportPayload.remoteClientId)
                .append("remotePeerConnectionId", reportPayload.remotePeerConnectionId)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("ssrc", reportPayload.ssrc)
                .append("packetsReceived", reportPayload.packetsReceived)
                .append("packetsLost", reportPayload.packetsLost)
                .append("jitter", reportPayload.jitter)
                .append("framesDropped", reportPayload.framesDropped)
                .append("lastPacketReceivedTimestamp", reportPayload.lastPacketReceivedTimestamp)
                .append("headerBytesReceived", reportPayload.headerBytesReceived)
                .append("packetsDiscarded", reportPayload.packetsDiscarded)
                .append("fecPacketsReceived", reportPayload.fecPacketsReceived)
                .append("fecPacketsDiscarded", reportPayload.fecPacketsDiscarded)
                .append("bytesReceived", reportPayload.bytesReceived)
                .append("nackCount", reportPayload.nackCount)
                .append("totalProcessingDelay", reportPayload.totalProcessingDelay)
                .append("estimatedPlayoutTimestamp", reportPayload.estimatedPlayoutTimestamp)
                .append("jitterBufferDelay", reportPayload.jitterBufferDelay)
                .append("jitterBufferTargetDelay", reportPayload.jitterBufferTargetDelay)
                .append("jitterBufferEmittedCount", reportPayload.jitterBufferEmittedCount)
                .append("jitterBufferMinimumDelay", reportPayload.jitterBufferMinimumDelay)
                .append("decoderImplementation", reportPayload.decoderImplementation)
                .append("framesDecoded", reportPayload.framesDecoded)
                .append("keyFramesDecoded", reportPayload.keyFramesDecoded)
                .append("frameWidth", reportPayload.frameWidth)
                .append("frameHeight", reportPayload.frameHeight)
                .append("framesPerSecond", reportPayload.framesPerSecond)
                .append("qpSum", reportPayload.qpSum)
                .append("totalDecodeTime", reportPayload.totalDecodeTime)
                .append("totalInterFrameDelay", reportPayload.totalInterFrameDelay)
                .append("totalSquaredInterFrameDelay", reportPayload.totalSquaredInterFrameDelay)
                .append("firCount", reportPayload.firCount)
                .append("pliCount", reportPayload.pliCount)
                .append("framesReceived", reportPayload.framesReceived)
                .append("packetsSent", reportPayload.packetsSent)
                .append("bytesSent", reportPayload.bytesSent)
                .append("remoteTimestamp", reportPayload.remoteTimestamp)
                .append("reportsSent", reportPayload.reportsSent)
                .append("roundTripTime", reportPayload.roundTripTime)
                .append("totalRoundTripTime", reportPayload.totalRoundTripTime)
                .append("roundTripTimeMeasurements", reportPayload.roundTripTimeMeasurements)
                ;
    }

    @Override
    public Document visitOutboundAudioTrackReport(Object payload) {

        var reportPayload = ((OutboundAudioTrackReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("label", reportPayload.label)
                .append("trackId", reportPayload.trackId)
                .append("sfuStreamId", reportPayload.sfuStreamId)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("ssrc", reportPayload.ssrc)
                .append("packetsSent", reportPayload.packetsSent)
                .append("bytesSent", reportPayload.bytesSent)
                .append("rid", reportPayload.rid)
                .append("headerBytesSent", reportPayload.headerBytesSent)
                .append("retransmittedPacketsSent", reportPayload.retransmittedPacketsSent)
                .append("retransmittedBytesSent", reportPayload.retransmittedBytesSent)
                .append("targetBitrate", reportPayload.targetBitrate)
                .append("totalEncodedBytesTarget", reportPayload.totalEncodedBytesTarget)
                .append("totalPacketSendDelay", reportPayload.totalPacketSendDelay)
                .append("averageRtcpInterval", reportPayload.averageRtcpInterval)
                .append("nackCount", reportPayload.nackCount)
                .append("encoderImplementation", reportPayload.encoderImplementation)
                .append("active", reportPayload.active)
                .append("packetsReceived", reportPayload.packetsReceived)
                .append("packetsLost", reportPayload.packetsLost)
                .append("jitter", reportPayload.jitter)
                .append("roundTripTime", reportPayload.roundTripTime)
                .append("totalRoundTripTime", reportPayload.totalRoundTripTime)
                .append("fractionLost", reportPayload.fractionLost)
                .append("roundTripTimeMeasurements", reportPayload.roundTripTimeMeasurements)
                .append("relayedSource", reportPayload.relayedSource)
                .append("audioLevel", reportPayload.audioLevel)
                .append("totalAudioEnergy", reportPayload.totalAudioEnergy)
                .append("totalSamplesDuration", reportPayload.totalSamplesDuration)
                .append("echoReturnLoss", reportPayload.echoReturnLoss)
                .append("echoReturnLossEnhancement", reportPayload.echoReturnLossEnhancement)
                .append("droppedSamplesDuration", reportPayload.droppedSamplesDuration)
                .append("droppedSamplesEvents", reportPayload.droppedSamplesEvents)
                .append("totalCaptureDelay", reportPayload.totalCaptureDelay)
                .append("totalSamplesCaptured", reportPayload.totalSamplesCaptured)

                ;
    }

    @Override
    public Document visitOutboundVideoTrackReport(Object payload) {

        var reportPayload = ((OutboundVideoTrackReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("clientId", reportPayload.clientId)
                .append("userId", reportPayload.userId)
                .append("peerConnectionId", reportPayload.peerConnectionId)
                .append("label", reportPayload.label)
                .append("trackId", reportPayload.trackId)
                .append("sfuStreamId", reportPayload.sfuStreamId)
                .append("sampleSeq", reportPayload.sampleSeq)
                .append("ssrc", reportPayload.ssrc)
                .append("packetsSent", reportPayload.packetsSent)
                .append("bytesSent", reportPayload.bytesSent)
                .append("rid", reportPayload.rid)
                .append("headerBytesSent", reportPayload.headerBytesSent)
                .append("retransmittedPacketsSent", reportPayload.retransmittedPacketsSent)
                .append("retransmittedBytesSent", reportPayload.retransmittedBytesSent)
                .append("targetBitrate", reportPayload.targetBitrate)
                .append("totalEncodedBytesTarget", reportPayload.totalEncodedBytesTarget)
                .append("totalPacketSendDelay", reportPayload.totalPacketSendDelay)
                .append("averageRtcpInterval", reportPayload.averageRtcpInterval)
                .append("nackCount", reportPayload.nackCount)
                .append("encoderImplementation", reportPayload.encoderImplementation)
                .append("active", reportPayload.active)
                .append("frameWidth", reportPayload.frameWidth)
                .append("frameHeight", reportPayload.frameHeight)
                .append("framesPerSecond", reportPayload.framesPerSecond)
                .append("framesSent", reportPayload.framesSent)
                .append("hugeFramesSent", reportPayload.hugeFramesSent)
                .append("framesEncoded", reportPayload.framesEncoded)
                .append("keyFramesEncoded", reportPayload.keyFramesEncoded)
                .append("qpSum", reportPayload.qpSum)
                .append("totalEncodeTime", reportPayload.totalEncodeTime)
                .append("qualityLimitationDurationNone", reportPayload.qualityLimitationDurationNone)
                .append("qualityLimitationDurationCPU", reportPayload.qualityLimitationDurationCPU)
                .append("qualityLimitationDurationBandwidth", reportPayload.qualityLimitationDurationBandwidth)
                .append("qualityLimitationDurationOther", reportPayload.qualityLimitationDurationOther)
                .append("qualityLimitationReason", reportPayload.qualityLimitationReason)
                .append("qualityLimitationResolutionChanges", reportPayload.qualityLimitationResolutionChanges)
                .append("firCount", reportPayload.firCount)
                .append("pliCount", reportPayload.pliCount)
                .append("packetsReceived", reportPayload.packetsReceived)
                .append("packetsLost", reportPayload.packetsLost)
                .append("jitter", reportPayload.jitter)
                .append("roundTripTime", reportPayload.roundTripTime)
                .append("totalRoundTripTime", reportPayload.totalRoundTripTime)
                .append("fractionLost", reportPayload.fractionLost)
                .append("roundTripTimeMeasurements", reportPayload.roundTripTimeMeasurements)
                .append("framesDropped", reportPayload.framesDropped)
                .append("relayedSource", reportPayload.relayedSource)
                .append("width", reportPayload.width)
                .append("height", reportPayload.height)
                .append("frames", reportPayload.frames)
                ;
    }

    @Override
    public Document visitSfuEventReport(Object payload) {

        var reportPayload = ((SfuEventReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("sfuId", reportPayload.sfuId)
                .append("callId", reportPayload.callId)
                .append("transportId", reportPayload.transportId)
                .append("mediaStreamId", reportPayload.mediaStreamId)
                .append("mediaSinkId", reportPayload.mediaSinkId)
                .append("sctpStreamId", reportPayload.sctpStreamId)
                .append("rtpPadId", reportPayload.rtpPadId)
                .append("name", reportPayload.name)
                .append("message", reportPayload.message)
                .append("value", reportPayload.value)
                .append("attachments", reportPayload.attachments);
    }

    @Override
    public Document visitSfuMetaReport(Object payload) {
        var reportPayload = ((SfuMetaReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("sfuId", reportPayload.sfuId)
                .append("callId", reportPayload.callId)
                .append("transportId", reportPayload.transportId)
                .append("mediaStreamId", reportPayload.mediaStreamId)
                .append("mediaSinkId", reportPayload.mediaSinkId)
                .append("sctpStreamId", reportPayload.sctpStreamId)
                .append("rtpPadId", reportPayload.rtpPadId)
                .append("type", reportPayload.type)
                .append("payload", reportPayload.payload);
    }

    @Override
    public Document visitSfuExtensionReport(Object payload) {
        var reportPayload = ((SfuExtensionReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("sfuId", reportPayload.sfuId)
                .append("extensionType", reportPayload.extensionType)
                .append("payload", reportPayload.payload);
    }

    @Override
    public Document visitSfuTransportReport(Object payload) {
        var reportPayload = ((SFUTransportReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("sfuId", reportPayload.sfuId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("internal", reportPayload.internal)
                .append("transportId", reportPayload.transportId)
                .append("dtlsState", reportPayload.dtlsState)
                .append("iceState", reportPayload.iceState)
                .append("sctpState", reportPayload.sctpState)
                .append("iceRole", reportPayload.iceRole)
                .append("localAddress", reportPayload.localAddress)
                .append("localPort", reportPayload.localPort)
                .append("protocol", reportPayload.protocol)
                .append("remoteAddress", reportPayload.remoteAddress)
                .append("remotePort", reportPayload.remotePort)
                .append("rtpBytesReceived", reportPayload.rtpBytesReceived)
                .append("rtpBytesSent", reportPayload.rtpBytesSent)
                .append("rtpPacketsReceived", reportPayload.rtpPacketsReceived)
                .append("rtpPacketsSent", reportPayload.rtpPacketsSent)
                .append("rtpPacketsLost", reportPayload.rtpPacketsLost)
                .append("rtxBytesReceived", reportPayload.rtxBytesReceived)
                .append("rtxBytesSent", reportPayload.rtxBytesSent)
                .append("rtxPacketsReceived", reportPayload.rtxPacketsReceived)
                .append("rtxPacketsSent", reportPayload.rtxPacketsSent)
                .append("rtxPacketsLost", reportPayload.rtxPacketsLost)
                .append("rtxPacketsDiscarded", reportPayload.rtxPacketsDiscarded)
                .append("sctpBytesReceived", reportPayload.sctpBytesReceived)
                .append("sctpBytesSent", reportPayload.sctpBytesSent)
                .append("sctpPacketsReceived", reportPayload.sctpPacketsReceived)
                .append("sctpPacketsSent", reportPayload.sctpPacketsSent);
    }

    @Override
    public Document visitSfuInboundRtpPadReport(Object payload) {
        var reportPayload = ((SfuInboundRtpPadReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("sfuId", reportPayload.sfuId)
                .append("marker", reportPayload.marker)
                .append("internal", reportPayload.internal)
                .append("timestamp", reportPayload.timestamp)
                .append("transportId", reportPayload.transportId)
                .append("sfuStreamId", reportPayload.sfuStreamId)
                .append("remoteSfuId", reportPayload.remoteSfuId)
                .append("remoteTransportId", reportPayload.remoteTransportId)
                .append("remoteSinkId", reportPayload.remoteSinkId)
                .append("remoteRtpPadId", reportPayload.remoteRtpPadId)
                .append("rtpPadId", reportPayload.rtpPadId)
                .append("ssrc", reportPayload.ssrc)
                .append("trackId", reportPayload.trackId)
                .append("clientId", reportPayload.clientId)
                .append("callId", reportPayload.callId)
                .append("mediaType", reportPayload.mediaType)
                .append("payloadType", reportPayload.payloadType)
                .append("mimeType", reportPayload.mimeType)
                .append("clockRate", reportPayload.clockRate)
                .append("sdpFmtpLine", reportPayload.sdpFmtpLine)
                .append("rid", reportPayload.rid)
                .append("rtxSsrc", reportPayload.rtxSsrc)
                .append("targetBitrate", reportPayload.targetBitrate)
                .append("voiceActivityFlag", reportPayload.voiceActivityFlag)
                .append("firCount", reportPayload.firCount)
                .append("pliCount", reportPayload.pliCount)
                .append("nackCount", reportPayload.nackCount)
                .append("sliCount", reportPayload.sliCount)
                .append("packetsLost", reportPayload.packetsLost)
                .append("packetsReceived", reportPayload.packetsReceived)
                .append("packetsDiscarded", reportPayload.packetsDiscarded)
                .append("packetsRepaired", reportPayload.packetsRepaired)
                .append("packetsFailedDecryption", reportPayload.packetsFailedDecryption)
                .append("packetsDuplicated", reportPayload.packetsDuplicated)
                .append("fecPacketsReceived", reportPayload.fecPacketsReceived)
                .append("fecPacketsDiscarded", reportPayload.fecPacketsDiscarded)
                .append("bytesReceived", reportPayload.bytesReceived)
                .append("rtcpSrReceived", reportPayload.rtcpSrReceived)
                .append("rtcpRrSent", reportPayload.rtcpRrSent)
                .append("rtxPacketsReceived", reportPayload.rtxPacketsReceived)
                .append("rtxPacketsDiscarded", reportPayload.rtxPacketsDiscarded)
                .append("framesReceived", reportPayload.framesReceived)
                .append("framesDecoded", reportPayload.framesDecoded)
                .append("keyFramesDecoded", reportPayload.keyFramesDecoded)
                .append("fractionLost", reportPayload.fractionLost)
                .append("jitter", reportPayload.jitter)
                .append("roundTripTime", reportPayload.roundTripTime);

    }

    @Override
    public Document visitSfuOutboundRtpPadReport(Object payload) {

        var reportPayload = ((SfuOutboundRtpPadReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("sfuId", reportPayload.sfuId)
                .append("marker", reportPayload.marker)
                .append("internal", reportPayload.internal)
                .append("timestamp", reportPayload.timestamp)
                .append("transportId", reportPayload.transportId)
                .append("sfuStreamId", reportPayload.sfuStreamId)
                .append("sfuSinkId", reportPayload.sfuSinkId)
                .append("rtpPadId", reportPayload.rtpPadId)
                .append("ssrc", reportPayload.ssrc)
                .append("callId", reportPayload.callId)
                .append("clientId", reportPayload.clientId)
                .append("trackId", reportPayload.trackId)
                .append("mediaType", reportPayload.mediaType)
                .append("payloadType", reportPayload.payloadType)
                .append("mimeType", reportPayload.mimeType)
                .append("clockRate", reportPayload.clockRate)
                .append("sdpFmtpLine", reportPayload.sdpFmtpLine)
                .append("rid", reportPayload.rid)
                .append("rtxSsrc", reportPayload.rtxSsrc)
                .append("targetBitrate", reportPayload.targetBitrate)
                .append("voiceActivityFlag", reportPayload.voiceActivityFlag)
                .append("firCount", reportPayload.firCount)
                .append("pliCount", reportPayload.pliCount)
                .append("nackCount", reportPayload.nackCount)
                .append("sliCount", reportPayload.sliCount)
                .append("packetsLost", reportPayload.packetsLost)
                .append("packetsSent", reportPayload.packetsSent)
                .append("packetsDiscarded", reportPayload.packetsDiscarded)
                .append("packetsRetransmitted", reportPayload.packetsRetransmitted)
                .append("packetsFailedEncryption", reportPayload.packetsFailedEncryption)
                .append("packetsDuplicated", reportPayload.packetsDuplicated)
                .append("fecPacketsSent", reportPayload.fecPacketsSent)
                .append("fecPacketsDiscarded", reportPayload.fecPacketsDiscarded)
                .append("bytesSent", reportPayload.bytesSent)
                .append("rtcpSrSent", reportPayload.rtcpSrSent)
                .append("rtcpRrReceived", reportPayload.rtcpRrReceived)
                .append("rtxPacketsSent", reportPayload.rtxPacketsSent)
                .append("rtxPacketsDiscarded", reportPayload.rtxPacketsDiscarded)
                .append("framesSent", reportPayload.framesSent)
                .append("framesEncoded", reportPayload.framesEncoded)
                .append("keyFramesEncoded", reportPayload.keyFramesEncoded)
                .append("roundTripTime", reportPayload.roundTripTime)
                ;
    }

    @Override
    public Document visitSctpStreamReport(Object payload) {
        var reportPayload = ((SfuSctpStreamReport) payload);
        return new Document()
                .append("serviceId", reportPayload.serviceId)
                .append("mediaUnitId", reportPayload.mediaUnitId)
                .append("sfuId", reportPayload.sfuId)
                .append("marker", reportPayload.marker)
                .append("timestamp", reportPayload.timestamp)
                .append("callId", reportPayload.callId)
                .append("roomId", reportPayload.roomId)
                .append("transportId", reportPayload.transportId)
                .append("streamId", reportPayload.streamId)
                .append("label", reportPayload.label)
                .append("protocol", reportPayload.protocol)
                .append("sctpSmoothedRoundTripTime", reportPayload.sctpSmoothedRoundTripTime)
                .append("sctpCongestionWindow", reportPayload.sctpCongestionWindow)
                .append("sctpReceiverWindow", reportPayload.sctpReceiverWindow)
                .append("sctpMtu", reportPayload.sctpMtu)
                .append("sctpUnackData", reportPayload.sctpUnackData)
                .append("messageReceived", reportPayload.messageReceived)
                .append("messageSent", reportPayload.messageSent)
                .append("bytesReceived", reportPayload.bytesReceived)
                .append("bytesSent", reportPayload.bytesSent);
    }
}
