@startuml
skinparam handwritten true
skinparam roundcorner 20
skinparam monochrome true
skinparam arrowThickness 2
skinparam BoxPadding 60



component observer
component "Client-Monitor" as client
component "Sfu-Monitor" as sfu
database "Database" as database

client -[hidden]d-> sfu
sfu ..r..> [observer] : Samples
client ..r.> [observer] : Samples
[observer] ..r..> database: Reports


@enduml
