@startuml
skinparam handwritten true
skinparam roundcorner 20
skinparam monochrome true
skinparam arrowThickness 2
skinparam BoxPadding 60



cloud "Your Cloud" #transparent {
	component observer
}
() WebRTCApp as client
() ReportProcessor as processor


client ..r..> [observer] : Sample
[observer] ..r..> processor: Report


@enduml
