package org.observertc.webrtc.common.reports;

public enum ReportType {
	INITIATED_CALL,
	FINISHED_CALL,
	JOINED_PEER_CONNECTION,
	DETACHED_PEER_CONNECTION,

	INBOUND_RTP_REPORT,
	OUTBOUND_RTP_REPORT,
	REMOTE_INBOUND_RTP_REPORT,

	ICE_CANDIDATE_PAIR_REPORT,
	ICE_LOCAL_CANDIDATE_REPORT,
	ICE_REMOTE_CANDIDATE_REPORT,
	MEDIA_SOURCE_REPORT,
	TRACK_REPORT,


	@Deprecated
	INBOUND_STREAM_REPORT,
	@Deprecated
	REMOTE_INBOUND_STREAM_REPORT,
	@Deprecated
	OUTBOUND_STREAM_REPORT,
}