package org.observertc.webrtc.common.reports;

public enum ReportType {
	INITIATED_CALL,
	FINISHED_CALL,
	JOINED_PEER_CONNECTION,
	DETACHED_PEER_CONNECTION,
	INBOUND_STREAM_REPORT,
	REMOTE_INBOUND_STREAM_REPORT,
	OUTBOUND_STREAM_REPORT,

	INBOUND_RTP_REPORT,
	OUTBOUND_RTP_REPORT,
	REMOTE_INBOUND_RTP_REPORT,

	ICE_CANDIDATE_PAIR_REPORT,
}