package org.observertc.webrtc.common.reports;

public enum ReportType {
	INITIATED_CALL,
	FINISHED_CALL,
	JOINED_PEER_CONNECTION,
	DETACHED_PEER_CONNECTION,
	INBOUND_STREAM_SAMPLE,
	REMOTE_INBOUND_STREAM_SAMPLE,
	OUTBOUND_STREAM_SAMPLE,
	@Deprecated
	MEDIA_STREAM_SAMPLE
}